ARG BASE_IMAGE

FROM $BASE_IMAGE AS build

ENV GOPATH=/app/go

WORKDIR /app/homonculus

COPY go.mod go.sum /app/homonculus/
RUN go mod download -x

COPY pkg/ /app/homonculus/pkg
COPY cmd/ /app/homonculus/cmd
COPY internal/ /app/homonculus/internal

RUN go build -v -o $GOPATH/bin/homonculus ./cmd

COPY templates /app/homonculus/templates
COPY examples /app/homonculus/examples
COPY examples/homonculus.yaml.example /app/homonculus/homonculus.yaml
